### ISSUE TITLE
Docker autodiscovery hangs for remote hosts

### ISSUE THREAD

**Issue by marcogiorgio** [xpipe-io/xpipe#106] opened 2023-11-28 11:41 UTC
Hi,
I am trying to add some remote hosts using SSH, but the automatic connection scan hangs while trying to discover Docker:
![image](https://github.com/xpipe-io/xpipe/assets/78936558/271e22bc-1562-4bab-8db3-a5c9b489ff12)

![image](https://github.com/xpipe-io/xpipe/assets/78936558/77d06004-02f7-4448-aef6-2f0cd07c1015)

Do I need to add the ssh user I am using to the `docker` group in the remote host in order for this feature to work?

I am using Linux Mint 21.2

Thanks

**Comment by crschnick** [comment] 2023-11-28 12:05
In theory the user group does not matter, it will dynamically elevate with sudo if required.

What you can do is go to the settings menu -> Troubleshooting -> Launch in debug mode. Then you should see in the console window where it is getting stuck

**Comment by marcogiorgio** [comment] 2023-11-28 12:39
Ah thanks, I was able to figure out why it wasn't working:
I've configured the SSH auth using a private key and I didn't specify the password. Hence, when it tried do do the elevation it couldn't because there was no password. It might be useful to add a warning such as `password may be required for sudo elevation`, or something like this

**Comment by crschnick** [comment] 2023-11-28 12:55
Hmm I have to see what went wrong there because that should already be happening. I will keep this issue open for that

**Comment by crschnick** [comment] 2023-11-28 19:32
I tried to reproduce it but did not manage it. In my case, whenever a password is required and none is available, it will show the expected error: 

![image](https://github.com/xpipe-io/xpipe/assets/72509152/db633169-145d-4bce-b75b-8a5d25cf464b)

So even if it works for you, it would be helpful if you could remove the password again from the SSH connection and try to add docker containers in debug mode to see what is getting executed.

**Comment by marcogiorgio** [comment] 2023-11-29 19:09
hi,
here are the logs I collected in debug mode after removing the password:

<details>
  <summary>logs</summary>
  
  ```
  20:01:16:558 - trace: [proc] Closing command normally {
    manageParent=false
}
20:01:16:558 - trace: [proc] Starting command execution ... {
    baseCommand=test -S /var/run/docker.sock && test -w /var/run/docker.sock
    shellType=bash
    elevated=false
    workingDirectory=null
}
20:01:16:558 - trace: [proc] Writing line {
    line=echo '10541fe7-0bc9-40f4-8f88-ca4cefb7fb41';echo '10541fe7-0bc9-40f4-8f88-ca4cefb7fb41' 1>&2;test -S /var/run/docker.sock && test -w /var/run/docker.sock;echo '1449db61-9a23-4f59-944f-ad0116670db3'${?}END;echo '1449db61-9a23-4f59-944f-ad0116670db3' 1>&2
}
20:01:16:559 - trace: [proc] Stdout finished. Reading exit code ...
20:01:16:559 - trace: [proc] Stderr finished {
    finishReason=NORMAL_FINISH
}
20:01:16:559 - trace: [proc] Read: 1END
20:01:16:559 - debug: [proc] Command finished {
    command=test -S /var/run/docker.sock && test -w /var/run/docker.sock
    finishReason=NORMAL_FINISH
    exitCode=1
}
20:01:16:559 - trace: [proc] Command state switched to finished
20:01:16:559 - trace: [proc] Read stderr {
    output=
}
20:01:16:559 - trace: [proc] Read stdout {
    output=
}
20:01:16:559 - trace: [proc] Closing command normally {
    manageParent=false
}
20:01:16:559 - trace: [proc] Starting command execution ... {
    baseCommand=docker version
    shellType=bash
    elevated=true
    workingDirectory=null
}
20:01:16:560 - trace: [proc] Starting command execution ... {
    baseCommand=SUDO_ASKPASS=/bin/false sudo -A -- bash -c 'echo hi'
    shellType=bash
    elevated=false
    workingDirectory=null
}
20:01:16:560 - trace: [proc] Writing line {
    line=echo '5db56d0e-4a06-4938-b62b-59c8b631e6a7';echo '5db56d0e-4a06-4938-b62b-59c8b631e6a7' 1>&2;SUDO_ASKPASS=/bin/false sudo -A -- bash -c 'echo hi';echo '4d3a19ab-bff6-43d5-8ed1-c5fc4b8e36fc'${?}END;echo '4d3a19ab-bff6-43d5-8ed1-c5fc4b8e36fc' 1>&2
}
20:01:16:578 - trace: [proc] Stderr finished {
    finishReason=NORMAL_FINISH
}
20:01:16:578 - trace: [proc] Stdout finished. Reading exit code ...
20:01:16:578 - trace: [proc] Read stderr {
    output=
    | sudo: no password was provided
    | sudo: a password is required
}
20:01:16:578 - trace: [proc] Read: 1END
20:01:16:578 - debug: [proc] Command finished {
    command=SUDO_ASKPASS=/bin/false sudo -A -- bash -c 'echo hi'
    finishReason=NORMAL_FINISH
    exitCode=1
}
20:01:16:578 - trace: [proc] Command state switched to finished
20:01:16:578 - trace: [proc] Read stdout {
    output=
}
20:01:16:578 - trace: [proc] Closing command normally {
    manageParent=false
}
20:01:16:578 - debug: [proc] Determined elevation config {
    requiresPassword=true
}
20:01:16:578 - trace: [proc] Using password-less sudo elevation {
    requiresPassword=true
    hasPasswordSupplier=false
}
20:01:16:578 - trace: [proc] Writing line {
    line=SUDO_ASKPASS=/bin/false sudo -A -- bash -c 'echo '\''34efc389-165c-46c5-8ef2-666422ebd13c'\'';echo '\''34efc389-165c-46c5-8ef2-666422ebd13c'\'' 1>&2;docker version;echo '\''b7d715d0-95e9-4677-a5b8-c55ec4144287'\''${?}END;echo '\''b7d715d0-95e9-4677-a5b8-c55ec4144287'\'' 1>&2'
}
20:01:24:078 - debug: [proc] Command finished {
    command=docker version
    finishReason=START_TIMEOUT
    exitCode=-80003
}
20:01:24:078 - trace: [proc] Stderr finished {
    finishReason=START_TIMEOUT
}
20:01:24:078 - trace: [proc] Command timed out
  ```
  
</details>

**Comment by crschnick** [comment] 2023-11-29 20:15
Thanks for the help. So it seems like everything is detected correctly but it is still trying to use password-less sudo, I should be able to fix that.

However, even though it is not doing it correctly, the command should return after a few seconds and the loading icon should go away. Does that also happen for you or is it staying there indefinitely?

**Comment by marcogiorgio** [comment] 2023-11-29 20:18
the icon stays there indefinitely :loop:

**Comment by crschnick** [comment] 2023-11-29 20:57
Ok managed to reproduce it, that should be fixable.

**Comment by crschnick** [comment] 2023-12-02 12:14
This should be fixed in the latest PTB release: https://github.com/xpipe-io/xpipe-ptb/releases/tag/1.7.9-5

**Comment by marcogiorgio** [comment] 2023-12-02 17:13
I've tested the new build and I confirm it's working. Thanks! :smile:

**Comment by crschnick** [comment] 2023-12-05 15:58
1.7.9 is now released

**Closed** 2023-12-06 02:14 UTC
Labels: bug
