### ISSUE TITLE
"Unable to determine POSIX shell" when using Fig

### ISSUE THREAD

**Issue by Fusion** [xpipe-io/xpipe#55] opened 2023-07-08 19:07 UTC
MacbookPro M1:

For instance, running

```Xpipe daemon mode gui```

Error:

```A terminal error occurred```
```Unable to determine POSIX shell: ]697;OSCLock=72b8dbe7-af46-421a-b5b5-c23abb425ede]697;PreExec-NoEnumerate a```

Stack trace:

```java.lang.IllegalStateException: Unable to determine POSIX shell: ]697;OSCLock=72b8dbe7-af46-421a-b5b5-c23abb425ede]697;PreExec-NoEnumerate a
at io.xpipe.ext.procx.util.b.a(SourceFile:217)
at io.xpipe.ext.procx.c.start(SourceFile:226)
at io.xpipe.core.impl.LocalStore.init(LocalStore.java:17)
at io.xpipe.app.core.mode.BaseMode.initialSetup(BaseMode.java:41)
at io.xpipe.app.core.mode.PlatformMode.initialSetup(PlatformMode.java:112)
at io.xpipe.app.core.mode.OperationMode.set(OperationMode.java:239)
at io.xpipe.app.core.mode.OperationMode.switchTo(OperationMode.java:137)
at io.xpipe.app.launcher.LauncherCommand.call(LauncherCommand.java:121)
at io.xpipe.app.launcher.LauncherCommand.call(LauncherCommand.java:23)
at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
at picocli.CommandLine.access$1500(CommandLine.java:148)
at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
at picocli.CommandLine.execute(CommandLine.java:2170)
at io.xpipe.app.launcher.LauncherCommand.runLauncher(LauncherCommand.java:63)
at io.xpipe.app.core.mode.OperationMode.init(OperationMode.java:106)
at io.xpipe.app.Main.main(Main.java:15)
```

**Comment by crschnick** [comment] 2023-07-08 19:11
What kind of things do you have in your profile files of your system shell (probably zsh in that case)? I see some ANSI escape codes there that shouldn't be normally printed in a dumb terminal environment.

**Comment by Fusion** [comment] 2023-07-08 20:00
I see so that's what this is. Yes, my zsh  prompt is very far from a dumb terminal.
I guess you are running a local shell to determine what my environment looks like.
Perhaps there's some environment variable or otherwise, that I could detect and not display anything confusing?
For instance, right now if I detect a non-interactive shell I do not apply any customization:

Top of my ~/.zshrc:
```
  case $- in                                                                                                                                                                                                                                                                            
      *i*) ;;                                                                                                                                                                                                                                                                           
        *) return;;                                                                                                                                                                                                                                                                     
  esac  
```

**Comment by crschnick** [comment] 2023-07-08 20:05
XPipe usually sets the environment variable `TERM=dumb`. However, I just realized that it does not do that for the local shell itself right now, only for sub shells of it.

So I guess currently there isn't a good way to detect this in your profile, but probably in the next XPipe release you will be able to check for `TERM=dumb`.

**Comment by crschnick** [comment] 2023-07-08 20:22
If you want to be clever about it, you can work around this issue by just executing `TERM=dumb /Applications/XPipe.app/Contents/MacOS/xpiped`, that will actually produce the desired behavior and you can check in your profile files for that.

**Comment by crschnick** [comment] 2023-07-08 20:24
That will start the daemon directly. If you use something like the `xpipe` executable in your path to start it, environment variables will not be passed to the daemon.

**Comment by crschnick** [comment] 2023-07-09 06:44
I pushed a staging test release that hopefully fixes this: https://github.com/xpipe-io/xpipe_staging/releases/tag/1.3.1 . You can just use the portable x86_64 version from there to test it, the installer replaces your current installation and that is not what you want. The x86_64 version might be a little slow on your ARM machine but it should work. Once the ARM build pipeline is functional I can also provide automatically generated ARM builds, but that is not possible yet.

**Comment by Fusion** [comment] 2023-07-09 08:00
Thanks. Weirdly, I am still getting the same issue. I should have mentioned earlier that I tried your suggested workaround and it did not work either.

**Comment by crschnick** [comment] 2023-07-09 08:14
How are you checking for the variable in your profile and what exactly do your prompt customizations do? It might be possible that the prompt stuff is already initialized when you first start any terminal. If you then launch xpipe from that terminal, the prompt customization is already present in the environment.

Ideally the prompt logic itself should respect the TERM variable, a static check at the top of your profile files might not be sufficient.

One solution would be for XPipe to just not run the profile files for the local system shell, but this would result in an incomplete Path, so that is also bad.

Maybe there are a few more ways to signal that no ANSI escape codes should be used by any command, I will have to look into that.

**Comment by Fusion** [comment] 2023-07-09 21:21
OK, got it!
As usual, user error. Or more specifically I still had [Fig](https://fig.io/) installed. And Fig is highly invasive. It will rewrite your prompts on-the-fly.
So, one for the FAQ, I guess :)

**Comment by crschnick** [comment] 2023-07-10 03:17
Ok, so I familiarized myself with Fig and it seems like it does a bad job at working together with anything outside of their product (maybe that is by design though).

I think the best option here would be to update the error message that is shown when we are not able to determine the shell type to include possible reasons such as custom prompts.

For the future, it would definitely be possible to somehow detect and maybe integrate to some degree with products such as Fig, but that is also dependent on how well they expose their settings to the outside.

**Comment by crschnick** [comment] 2023-07-10 16:55
I thought about a potential solution by hardening the shell type detection logic against these prompts as we can't disable them easily, let me see whether the implementation will actually work.

Because I think the only place where the prompts will be interfering is in the shell detection, everything else after that should work fine even with the prompts.

**Comment by crschnick** [comment] 2023-07-11 05:34
Can you try whether this build works for you with Fig enabled: https://github.com/xpipe-io/xpipe_staging/releases/tag/1.3.2

Essentially it now looks for anything resembling the printed information what shell type we are in, that should even work when the prompt is mixed in with the output.

**Comment by crschnick** [comment] 2023-07-13 14:35
With the default Fig configuration, the latest proper release (https://github.com/xpipe-io/xpipe/releases/tag/1.3.2) does correctly detect the shell type now for me. I briefly tested as many things as possible while Fig was enabled and didn't encounter any other issue.

However I can't guarantee that Fig won't intervene with something else, so let's see about that in the future.

(In case you downloaded the staging release, note that it is a incompatible version to the normal releases and won't get updates. So you would have to download and install a proper release again. I am in the process of completely separating both types of installation so in the future you can have staging and normal releases side by side.)

**Comment by crschnick** [comment] 2023-11-16 14:34
Whoops, it seems like I forgot to close this. It seems like this issue has outlived Fig, with it getting absorbed by amazon

**Closed by crschnick** 2023-11-16 14:34 UTC
Labels: bug, enhancement
