### ISSUE TITLE
Error when trying to open VM console

### ISSUE THREAD

**Issue by davidclaeysquinones** [xpipe-io/xpipe#377] opened 2024-11-21 08:17 UTC
I've a couple of VM's setup on my proxmox host.
Currently I'm using XPipe in windows.

When I try to open a terminal to a VM I get the following error :

`java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "io.xpipe.ext.proc.vm.d.getPort()" is null`

**Comment by crschnick** [comment] 2024-11-21 08:20
I think I already sent you an email about that. If you did not get that, I might have to check my mail settings as I recently upped the dmarc level

**Comment by crschnick** [comment] 2024-11-21 08:25
And for anyone else who also has this issue: That error is caused by an oversight when migrating VMs from older XPipe versions. I will fix that in the next release. Meanwhile, you can work around this issue, by right clicking the VM connection, click on edit, and fill in the port. The port property didn't exist in earlier versions, that is where this error is coming from.

**Comment by davidclaeysquinones** [comment] 2024-11-21 08:33
You did send a mail but it ended in the spam folder. Thanks you for responding so quickly.

**Comment by crschnick** [comment] 2024-11-23 14:20
This is now fixed in the latest release

**Closed by crschnick** 2024-11-23 14:20 UTC
Labels: bug
