### ISSUE TITLE
[Feature Request]   Export option allowing importing all configured hosts 

### ISSUE THREAD

**Issue by dwilliam62** [xpipe-io/xpipe#122] opened 2023-12-24 07:46 UTC
With Putty for example I can copy the config files and easily add them or sync them between systems. 

This would go a long way to making it easier to deploy at companies. 

ideally the export file would be encrypted with a password 

Thanks for this tool.   I just started using it today at home.

**Comment by crschnick** [comment] 2023-12-24 13:28
Have you tried the git vault functionality yet? That one tries to approach of syncing information between systems from a more modern angle. If the git integration does not fit your use case, I can think of also adding a normal export functionality.

If you set a vault master passphrase in the settings, it does encrypt the sensitive information. That also applies to the information then stored in the git repository.

**Comment by dwilliam62** [comment] 2023-12-24 19:25
I am looking at it now I think that will work.   It's more involved for sure.   At work we have SecureCRT.  We have a master config file that has not only hosts and VMs but commands for troubleshooting our product in their layered button bar feature.   I.e. if I am working on a subsystem of the product, I can select from a drop down and get all the relevant troubleshooting commands for that subsystem as buttons that will run those commands or scripts.   As it gets updated we can import and merge it as needed.   Not need to set up git, a git repo, a git server, etc...    Especially in non commercial settings     Hopefully something for future consideration.   Thank you

**Comment by crschnick** [comment] 2023-12-24 19:31
Interesting to hear about the actual work setups here. How exactly does the master config get shared in your case? Because I can see some problems here with importing and merging a config with multiple people working on it. That is why I went for using git as a platform, that solves many of these issues better.

The git repository is initialized then managed automatically, the only thing you need is a remote git host somewhere. For example, you can create private repositories for free on GitHub, so I also use that for my connection configurations.

**Comment by dwilliam62** [comment] 2023-12-24 21:32
I will try that because I am having no luck getting github to work.  I have
my SSH keys but it won't log in to github and I can't use password
authentication


In my case there is only myself so no worry about parallel access.

**Comment by crschnick** [comment] 2023-12-24 21:37
Hm yeah when starting out you will frequently encounter some issues with remote GitHub repositories. Most of the times SSH keys not working is caused by using a HTTP git remote url instead of an SSH-based on that should have the form `git@github.com:user/repo.git`. That also gives me the idea to verify that within xpipe, because right now we don't verify URLs.

**Comment by dwilliam62** [comment] 2023-12-24 21:49
Well that didn't work too well.   I can't copy the existing into the new
location?    It's back to initial state, only the localhost is seen

**Comment by crschnick** [comment] 2023-12-24 21:53
Right now you would have to manually copy the data to the new directory when moving it. I could implement an optional dialog to also move the entire data as well though. Right now this functionality to change the directory is primarily there so people can switch between different configs.

Assuming that you were using the default directory before, you can copy the contents of `<User Home>\.xpipe\storage` into your new directory on the shared drive.

**Comment by crschnick** [comment] 2023-12-24 21:54
I created #128 for this

**Comment by dwilliam62** [comment] 2023-12-24 22:05
I copied all the files in .xpipe

**Comment by dwilliam62** [comment] 2023-12-24 22:12
OK so I didn't notice xpipe vs. xpipe-ptb   but now all the saved settings
are gone on both Windows and Linux

I am back to square one

**Comment by crschnick** [comment] 2023-12-24 22:18
So if you are using the normal version and the PTB, they have different directories as you mentioned in .xpipe and .xpipe-ptb so they don't interfere. The settings and some other user data are always stored in `<home>/.xpipe` or `<home>/.xpipe-ptb`, they can't be moved. The only part that can be moved is the connection configuration storage in `<home>/.xpipe/storage`.

The settings should not be shared as they contain platform specific information, only the storage directory. So if you change the vault directory in the settings menu, it should always refer to the storage directory, not the parent directory `.xpipe` itself.

I should clarify that somewhere though, I can see how that is confusing.

**Comment by dwilliam62** [comment] 2023-12-24 22:47
Thanks.  Yeah I am not using both.  I removed the normal when installed
the PTB

  yeah so i am back to 0.  oh well.   I think I need to remove it all
clear the configs and start over.

 that way I won't cause some weird issue later on

**Comment by crschnick** [comment] 2023-12-24 23:06
I'm sorry for the problems this has caused you, I will definitely use this as a motivation to make the process more robust.

**Comment by dwilliam62** [comment] 2023-12-25 00:25
No worries!   I don't have hundred of servers or vms.  not a big deal.  I
may set up my own GIT server  Give that a try.

 thanks for the replies and the support.

**Comment by dwilliam62** [comment] 2023-12-25 02:05
So I set up GITEA in a container and it's working with the 1st system.
Hopefully I can try it on the Windows system next.
 don

**Comment by dwilliam62** [comment] 2023-12-25 06:18
I am not sure if it's working as designed but only entries in the "Default' are stored to the GIT repository.    The "All Connections"  hosts are not imported from the GIT repo.  I had to move all the connections to default first.  I don't knwo how some were default and some were "all"    Possibly the non default entries were the ones I cloned?

**Comment by crschnick** [comment] 2023-12-25 14:11
If you click on the settings entry on the category or right click it (i.e. the one's other than Default that you want to share), there should be an option to enable or disable sharing.

This is so that you don't share everything automatically so you can also have private connections as well.

**Comment by dwilliam62** [comment] 2023-12-25 19:06
Ahh   great thanks.

**Comment by crschnick** [comment] 2024-01-05 10:54
I guess we can close this?

While having a normal export option would be simpler for a lot of people, this would introduce new problems and I would have to support git and the import/export functionality. I think going forward focusing on git is the better option.

**Closed by crschnick** 2024-01-05 10:54 UTC

**Comment by dwilliam62** [comment] 2024-01-05 12:39
yes go ahead.   Maybe something to consider later on.

thank you
