### ISSUE TITLE
Error when connecting to Docker

### ISSUE THREAD

**Issue by saif-88** [xpipe-io/xpipe#107] opened 2023-12-06 13:03 UTC
Hello,

When connecting to Docker v19 (maybe the same for older version), i get this error

`Process returned exit code 1:
Template parsing error: template: :1:13: executing "" at <.State>: can't evaluate field State in type *formatter.containerContext`

And the details

`io.xpipe.core.process.ProcessOutputException: Process returned exit code 1:
Template parsing error: template: :1:13: executing "" at <.State>: can't evaluate field State in type *formatter.containerContext
at io.xpipe.core.process.ProcessOutputException.of(ProcessOutputException.java:36)
at io.xpipe.ext.proc.a.a(SourceFile:249)
at io.xpipe.ext.proc.a.readStdoutOrThrow(SourceFile:294)
at io.xpipe.ext.proc.docker.i.g(SourceFile:178)
at io.xpipe.ext.proc.docker.i.a(SourceFile:147)
at io.xpipe.ext.proc.docker.DockerCmdStore.listChildren(SourceFile:65)
at io.xpipe.app.storage.DataStorage.refreshChildren(DataStorage.java:230)
at io.xpipe.ext.base.action.RefreshStoreAction$Action.execute(RefreshStoreAction.java:26)
at io.xpipe.app.comp.store.StoreEntryWrapper.executeDefaultAction(StoreEntryWrapper.java:205)
at io.xpipe.app.comp.store.StoreEntryComp.lambda$createSimple$0(StoreEntryComp.java:101)
at io.xpipe.app.util.ThreadHelper.lambda$runFailableAsync$1(ThreadHelper.java:40)
at io.xpipe.app.util.ThreadHelper.lambda$wrap$0(ThreadHelper.java:19)
at java.lang.VirtualThread.run(VirtualThread.java:309)`

Xpipe Version 1.7.10

No problem with Docker v20

**Comment by crschnick** [comment] 2023-12-06 15:54
Yeah I think that is caused by older versions of docker not supporting that option. I'm not sure whether I want to support older versions, as that is quite some work.

Is there any reason why you run an old docker version?

**Comment by crschnick** [comment] 2023-12-07 14:18
So good news, it seems like I can replace .State with .Status, which also has the nice side effect of showing better status messages:
![image](https://github.com/xpipe-io/xpipe/assets/72509152/eb36e51d-7086-486a-8f88-8d9a3d04f804)

**Comment by crschnick** [comment] 2023-12-09 02:33
This has now been implemented in the latest PTB build at https://github.com/xpipe-io/xpipe-ptb, so you can try it out if you want

**Comment by saif-88** [comment] 2023-12-09 09:21
I will 😄😄😄

**Comment by crschnick** [comment] 2023-12-16 04:07
This feature is now released, you can try it out in the latest version

**Comment by crschnick** [comment] 2023-12-19 14:46
Closing this for now, feel free to reopen if something does not work as expected

**Closed by crschnick** 2023-12-19 14:46 UTC
