### ISSUE TITLE
Adding SSH connection to Cisco Device fails.

### ISSUE THREAD

**Issue by arcreigh** [xpipe-io/xpipe#94] opened 2023-10-30 17:42 UTC
I assume due to xpipe trying to figure out what kind of device is on the other side of the SSH connection it connects successfully but gets confused by the Cisco environment. Can we get a checkbox to disable discovery checking to allow connections to network devices that don't have "normal" *nix shell environments?

```
Shell opener normalization failed:
3750#echo "Checking what shell type we are in ..."
The command you have entered is available in the IOS.sh.
However, the shell is currently disabled. You can enable
it on this terminal by typing
   'term shell'
You can also enable it for all terminals by configuring the
   'shell processing full'
command. There is additional information in the man command.
For more information, enable shell, and then enter:
'man IOS.sh'
3750#echo -NoEnumerate "a"
The command you have entered is available in the IOS.sh.
However, the shell is currently disabled. You can enable
it on this terminal by typing
   'term shell'
You can also enable it for all terminals by configuring the
   'shell processing full'
command. There is additional information in the man command.
For more information, enable shell, and then enter:
'man IOS.sh'
3750#
3750#echo -NoEnumerate "a"
The command you have entered is available in the IOS.sh.
However, the shell is currently disabled. You can enable
it on this terminal by typing
   'term shell'
You can also enable it for all terminals by configuring the
   'shell processing full'
command. There is additional information in the man command.
For more information, enable shell, and then enter:
'man IOS.sh'
3750#
```

**Comment by crschnick** [comment] 2023-10-30 22:17
For that purpose I would try to use the `Custom Command -> Custom Terminal Command` connection in xpipe if your only intention is quickly booting up into a terminal. Anything more wouldn't be possible anyways if the shell is not recognized.

I will improve the descriptions in the application to highlight this.

**Comment by crschnick** [comment] 2023-10-30 22:21
If your SSH connection however also requires inputs like a password, then this can't be filled automatically with a custom terminal command.

I guess I can think of a solution to somehow disable shell type recognition for normal SSH connections if needed.

**Comment by arcreigh** [comment] 2023-10-30 22:23
Most network devices will require a password it still conforms to the normal SSH protocol but its not a unix device so your checks wont be valid. Maybe having a fallback in your error handling for generic SSH would be a good option?

**Comment by crschnick** [comment] 2023-10-30 22:32
Sadly I don't have any cisco hardware available to test, so I have to rely on your help here a little bit.

The issue is that I need to detect that we are in a cisco environment right away somehow. If I can't do this, and the normal shell detection logic is run, it will take like 10 seconds for the timeout handling to kick in and realize that we need to fallback to an unknown shell type.

I already do something like this for opnsense shells as they also require special handling. I guess I can just check for the output `The command you have entered is available in the IOS.sh.` and deduce that this is a Cisco environment. Or is this warning printed only in some Cisco environments and not in some others?

**Comment by crschnick** [comment] 2023-10-31 00:06
I just implemented my plan of checking for a specific output for cisco devices. Can you try whether the latest version in https://github.com/xpipe-io/xpipe-ptb works?

**Comment by arcreigh** [comment] 2023-10-31 00:17
So my recommendation would be to use `sh ver` short for show version which is ubiquitous across all cisco devices.
As there are 3 major different code bases IOS, IOS-XE, and NX-OS from there the output will tell you what code version is available what the underlying hardware is etc. Here is some example output from my 3750X

```
Cisco IOS Software, C3750E Software (C3750E-UNIVERSALK9-M), Version 15.2(4)E10, RELEASE SOFTWARE (fc2)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2020 by Cisco Systems, Inc.
Compiled Tue 31-Mar-20 13:22 by prod_rel_team

ROM: Bootstrap program is C3750E boot loader
BOOTLDR: C3750E Boot Loader (C3750X-HBOOT-M) Version 12.2(53r)SE2, RELEASE SOFTWARE (fc1)

3750 uptime is 26 weeks, 3 days, 7 hours, 13 minutes
System returned to ROM by power-on
System image file is "flash:/flash"
Last reload reason: power-on



This product contains cryptographic features and is subject to United
States and local country laws governing import, export, transfer and
use. Delivery of Cisco cryptographic products does not imply
third-party authority to import, export, distribute or use encryption.
Importers, exporters, distributors and users are responsible for
compliance with U.S. and local country laws. By using this product you
agree to comply with applicable laws and regulations. If you are unable
to comply with U.S. and local laws, return this product immediately.

A summary of U.S. laws governing Cisco cryptographic products may be found at:
http://www.cisco.com/wwl/export/crypto/tool/stqrg.html

If you require further assistance please contact us by sending email to
export@cisco.com.

License Level: ipservices
License Type: Permanent Right-To-Use
Next reload license Level: ipservices

cisco WS-C3750X-48P (PowerPC405) processor (revision A0) with 262144K bytes of memory.
Processor board ID FDO1605P1LZ
Last reset from power-on
4 Virtual Ethernet interfaces
1 FastEthernet interface
52 Gigabit Ethernet interfaces
2 Ten Gigabit Ethernet interfaces
The password-recovery mechanism is enabled.

512K bytes of flash-simulated non-volatile configuration memory.
Base ethernet MAC Address       : 44:2B:03:89:3C:80
Motherboard assembly number     : 73-12553-05
Motherboard serial number       : FDO1605187U
Model revision number           : A0
Motherboard revision number     : D0
Model number                    : WS-C3750X-48PF-S
Daughterboard assembly number   : 800-32727-01
Daughterboard serial number     : FDO160501H0
System serial number            : FDO1605P1LZ
Top Assembly Part Number        : 800-31324-02
Top Assembly Revision Number    : E0
Version ID                      : V02
CLEI Code Number                : COMJZ00ARB
Hardware Board Revision Number  : 0x03


Switch Ports Model                     SW Version            SW Image
------ ----- -----                     ----------            ----------
*    1 54    WS-C3750X-48P             15.2(4)E10            C3750E-UNIVERSALK9-M


Configuration register is 0xF
```

**Comment by crschnick** [comment] 2023-10-31 06:47
Well I will see what I can do with the version output. The problem is that it becomes very hard to properly read output if no normal shell commands are supported. Without echo I can't be sure where the output of one command starts and ends.

From my testing with mock output, checking for the string `The command you have entered is available in the IOS.sh` works for now at least. I plan to release this quick fix tomorrow with 1.7.3, maybe you find some time to quickly check whether the [PTB](https://github.com/xpipe-io/xpipe-ptb) works on real hardware until then so I can be sure.

**Comment by arcreigh** [comment] 2023-10-31 20:51
I do want to urge caution though if someone else out there runs IOS-XE / NX-OS you won't get the same response. 
So while this will likely work for me / anyone else running older 3750's which are end of life hardware your fix might not apply to everyone. I have an NX-OS device but it is not yet configured and I don't have SFPs to be able to properly test it.

**Comment by arcreigh** [comment] 2023-10-31 20:55
Ok now we are able to add the device but get an error on starting the connection
```
Shell did not start up in time:
3750#echo "Checking what shell type we are in ..."
The command you have entered is available in the IOS.sh.
However, the shell is currently disabled. You can enable
it on this terminal by typing
   'term shell'
You can also enable it for all terminals by configuring the
   'shell processing full'
command. There is additional information in the man command.
For more information, enable shell, and then enter:
'man IOS.sh'
3750#echo -NoEnumerate "a"
The command you have entered is available in the IOS.sh.
However, the shell is currently disabled. You can enable
it on this terminal by typing
   'term shell'
You can also enable it for all terminals by configuring the
   'shell processing full'
command. There is additional information in the man command.
For more information, enable shell, and then enter:
'man IOS.sh'
3750#echo "Checking whether we are in fish"
The command you have entered is available in the IOS.sh.
However, the shell is currently disabled. You can enable
it on this terminal by typing
   'term shell'
You can also enable it for all terminals by configuring the
   'shell processing full'
command. There is additional information in the man command.
For more information, enable shell, and then enter:
'man IOS.sh'
3750#echo "fish: $FISH_VERSION"
The command you have entered is available in the IOS.sh.
However, the shell is currently disabled. You can enable
it on this terminal by typing
   'term shell'
You can also enable it for all terminals by configuring the
   'shell processing full'
command. There is additional information in the man command.
For more information, enable shell, and then enter:
'man IOS.sh'
3750#
```

**Comment by crschnick** [comment] 2023-11-02 07:35
I think the task of supporting your cisco devices and others is going to be complicated. I had hoped that my quick fix would work, but as it does not, I would have to investigate this manually somehow to properly implement and test everything.

As I don't have any cisco hardware myself, I either have to maybe find someone near me to borrow one for a few days or purchase the cheapest used one that I can find.

I don't really like a checkbox to disable this discovery as you suggested, mainly because that would be confusing for users as you need to know what's happening in the background in order to understand why this option is necessary. However, I'm thinking about adding a special option to the error handler to mark the connection as having discovery disabled. That way, you still have the option to disable it but only if you actually need it.

**Comment by crschnick** [comment] 2023-11-03 05:48
So I though about the implementation and this discovery disable functionality will be added in 1.8.0 along with a more general shell type rework. Your case is not the only problematic one, fish shell also causes problems right now.

The system was not designed for these cases initially so I need to change several things there which takes some time, so stay tuned for 1.8

**Comment by crschnick** [comment] 2023-12-09 02:35
All right since I was not able to get my hands on a cisco device I have a couple of questions:
- How does it handle connections without a tty? E.g. does it also work if you connect with ssh -T user@host?
- Where are the errors written to? E.g. if you input a command that does not exist, does it write to stdout or stderr?

**Comment by crschnick** [comment] 2024-02-21 03:24
Alright, the shell handling has been reworked to allow for dumb shell connections in 1.8 and is currently in testing at https://github.com/xpipe-io/xpipe-ptb.

To properly make this work for your case, I would need to know whether your device will print the error
```
The command you have entered is available in the IOS.sh.
However, the shell is currently disabled. You can enable
it on this terminal by typing
   'term shell'
You can also enable it for all terminals by configuring the
   'shell processing full'
command. There is additional information in the man command.
For more information, enable shell, and then enter:
'man IOS.sh'
``` to stdout or stderr. If I can identify a system, it is now trivial to add support for it as a dumb shell.

**Comment by arcreigh** [comment] 2024-02-21 14:08
Very likely yes, please do keep in mind though that the shell isn’t utilized in normal operations. Cisco has a custom CLI with three tiers of access. Zero level -> user -> privileged exec.To get from zero to user the “enable” command is utilized, and from user to priv “configure terminal” is used. There can be a separate enable password from privileged. But most of the time some form of TACACS will grant the ability to skip the enable to get straight to user. v/r Andrew CreighNetwork Engineercell: 304-707-4851On Feb 20, 2024, at 10:24 PM, Christopher Schnick ***@***.***> wrote:﻿
Alright, the shell handling has been reworked to allow for dumb shell connections in 1.8 and is currently in testing at https://github.com/xpipe-io/xpipe-ptb.
To properly make this work for your case, I would need to know whether your device will print the error
The command you have entered is available in the IOS.sh.
However, the shell is currently disabled. You can enable
it on this terminal by typing
   'term shell'
You can also enable it for all terminals by configuring the
   'shell processing full'
command. There is additional information in the man command.
For more information, enable shell, and then enter:
'man IOS.sh'
``` to stdout or stderr. If I can identify a system, it is now trivial to add support for it as a dumb shell. 


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by arcreigh** [comment] 2024-02-21 20:42
Yeah bad habit on my part for replying via my email instead of through github I edited my comment. 

Typically there is a designator character on the shell to tell you when you are in zero vs user vs priv.

hostname> is zero
hostname# is user
hostname(config) is privileged exec

So maybe searching the returned output can help you out?

**Comment by crschnick** [comment] 2024-02-21 20:44
I see about the character.

If you run `ssh user@host 2>/dev/null` to your cisco device, does it print any error messages? E.g. if you type an invalid command, is the error then swallowed by /dev/null or not?

**Comment by crschnick** [comment] 2024-04-13 18:30
This is now properly fixed in XPipe 9 at https://github.com/xpipe-io/xpipe-ptb for all cases with the introduction of a new option to not attempt to identify the system.

**Closed by crschnick** 2024-04-13 18:30 UTC
Labels: enhancement
