### ISSUE TITLE
File Manager does not save changes to temp files

### ISSUE THREAD

**Issue by blunweon** [xpipe-io/xpipe#300] opened 2024-07-16 09:09 UTC
First off, would like to say that I love this app and it has made me switch over to religiously only use this.

However, after recent updates, I noticed that when I opened temporary files to edit (e.g settings.yml) and after saving, the changes are not reflected in the filesystem.
![image](https://github.com/user-attachments/assets/123c3fea-5d17-4696-94f6-c9b8ffd55bf9)
![image](https://github.com/user-attachments/assets/80a13cbe-c9e0-4f9b-83cd-921ebae95884)
![image](https://github.com/user-attachments/assets/aa70a9f2-1e77-4605-9ce4-a66567fde7a7)

As you can see, after editing the settings.yml, it did not reflect the changes in the filesystem and was still labeled as last updated "17:02", which was when I used WinSCP to manually go in and edit it.

Please let me know if I am doing something wrong, which caused this issue.

**Comment by crschnick** [comment] 2024-07-16 09:16
So I haven't encountered this issue and am not able to reproduce this. Does this happen everywhere, all the time, or are there specific conditions? I assume this is Windows 11 with vscode as the editor?

**Comment by crschnick** [comment] 2024-07-16 09:31
I see that xpipe is using powershell as the local shell. It usually does that when cmd doesn't work as expected, maybe you got an error message about that on first launch.

You can see what happens if you go to Settings -> Local shell and disable the fallback.

I will test this with powershell

**Comment by crschnick** [comment] 2024-07-16 09:41
Ok so what you can do is go to Settings -> Troubleshoot -> Launch in debug mode. That should print all file editing details.

You can send me the logs per email or discord or alternatively only paste the relevant part here.

**Comment by crschnick** [comment] 2024-07-16 09:54
I see the issue, it's a bug on my end

**Comment by crschnick** [comment] 2024-07-16 10:07
It should check for time as well, but that is currently broken.

**Comment by crschnick** [comment] 2024-07-16 12:45
This should now be fixed in 10.1.1

**Closed as completed** 2024-07-19 09:07 UTC
