### ISSUE TITLE
No terminal appears when connecting to a target with default fish shell

### ISSUE THREAD

**Issue by padd1er** [xpipe-io/xpipe#183] opened 2024-01-26 13:51 UTC
I'm trying to connect from a win10 machine to my raspberry with the latest Pi OS Lite 64bit (target):
Release date: December 11th 2023
System: 64-bit
Kernel version: 6.1
Debian version: 12 (bookworm)

On host machine by default I use powershell (with starship) and Windows Terminal (also tried other available terminals for the below case, same issue).

Everything works fine while I have bash (with starship) as my main shell on target machine - new terminal window pops with a fresh connection.
But as soon as I switch target machine to fish (with starship) - no new terminal appears. Just nothing happens after shell check starts.

Attaching debug logs from both sessions:
[debug_bash.txt](https://github.com/xpipe-io/xpipe/files/14065525/debug_bash.txt)
[debug_fish.txt](https://github.com/xpipe-io/xpipe/files/14065526/debug_fish.txt)

**Comment by crschnick** [comment] 2024-01-26 13:57
Yeah that is a known limitation with fish. But in theory there should be an error window being shown after the connection times out that explains that fish is not supported as a log in shell. I assume that does not happen for you?

Essentially fish does not support an interactive mode without a tty, which xpipe does not provide when it first attempts a connection. I already raised the issue with the fish maintainers but they don't want to change that behavior.

**Comment by padd1er** [comment] 2024-01-26 14:47
Nope, there were no errors. Otherwise I wouldn't spend 2 days attempting to clear cache/storage/configs 😢

**Comment by crschnick** [comment] 2024-01-26 14:48
Oh well then that must be a bug. Did you alter the connections timeout in the settings menu?

Because there should be an error shown after some time when the shell is frozen and in addition it should mention in this case that this is related to fish.

**Comment by padd1er** [comment] 2024-01-26 14:52
Nope, 10 seconds as it was set by default.
![image](https://github.com/xpipe-io/xpipe/assets/156316516/1fd2932e-bd8f-492a-89a3-978e542f3c21)

Also, while we are on this - is it possible to work around this by passing `-t "bash"` somehow?

**Comment by crschnick** [comment] 2024-01-26 14:54
Hmm, I will try to reproduce that.

You can work around this by clicking on Find available connections -> Shell environments for the target system and then just launching a working shell environment in the terminal.

**Comment by crschnick** [comment] 2024-01-26 15:02
Edit: Nevermind, that shell environment approach will not work. You just have to use another login shell right now.

I will try to fix this problem soon with some workaround

**Comment by crschnick** [comment] 2024-01-26 17:56
So I tested this on my end and got the expected result: 
![grafik](https://github.com/xpipe-io/xpipe/assets/72509152/5cc5b775-7e45-4231-ab5a-63711bedcbd8)

In your debug log, is anything else printed after 10 seconds elapsed? For me it looks like this
```
18:49:20:578 - trace: [proc] Read: 
18:49:30:578 - trace: [proc] Read:  (no LF)
18:49:30:578 - trace: [proc] Writing line {
    line=echo "Shell did not respond in timeout interval. Now we are reading any possible error output and checking whether we are in fish"
}
```

**Comment by padd1er** [comment] 2024-01-26 19:05
Absolutely nothing.

Here's an example (at 20:01 I intentionally clicked another connection):
```
19:59:11:536 - trace: [proc] Read: 57231212-d965-4a28-9275-be5ada9f3899
19:59:11:536 - trace: [proc] Read:
19:59:11:536 - trace: [proc] Read: 3986ea86-a5f3-4e4d-9d9d-6e27cb807fac
19:59:11:536 - trace: [proc] Writing line {
    line=echo "Checking what shell type we are in ..."
}
19:59:11:536 - trace: [proc] Writing line {
    line=echo -NoEnumerate "a"
}
19:59:11:798 - trace: [proc] Read: Linux box 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64
19:59:11:798 - trace: [proc] Read:
19:59:11:799 - trace: [proc] Read: The programs included with the Debian GNU/Linux system are free software;
19:59:11:799 - trace: [proc] Read: the exact distribution terms for each program are described in the
19:59:11:799 - trace: [proc] Read: individual files in /usr/share/doc/*/copyright.
19:59:11:799 - trace: [proc] Read:
19:59:11:799 - trace: [proc] Read: Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
19:59:11:799 - trace: [proc] Read: permitted by applicable law.
20:01:06:955 - trace: [proc] Starting local process {
    command=cmd
}
20:01:06:957 - trace: [proc] Writing line {
    line=CHCP 65001 >NUL
}
20:01:06:970 - trace: [proc] Writing line {
    line=set TERM=dumb
}
```

**Comment by crschnick** [comment] 2024-01-26 21:04
Oh how are you authenticating? I think xpipe disables timeouts when a user input is required as that might take an arbitrary amount of time. Maybe I can think of a better solution here

**Comment by padd1er** [comment] 2024-01-27 16:06
I auth through an ssh-agent.
I've two connections - one was imported from my ssh config, another one was created manually. 

Imported connection settings:
![image](https://github.com/xpipe-io/xpipe/assets/156316516/a3380d7a-e358-4a50-8e10-d2aa5995f3ca)

Manually created connection settings:
![image](https://github.com/xpipe-io/xpipe/assets/156316516/c63569be-ab39-4776-ba91-129255f4387e)

**Comment by crschnick** [comment] 2024-01-27 16:12
Yeah it seems like this is due to the prompt setting for passwords then. I'm planning to throw out the part of the code that does not work with fish shell and hopefully find something better soon.

**Comment by crschnick** [comment] 2024-02-28 13:32
This should be fixed now in the latest release. Fish support is still a workaround and take a long time to initialize at first, but it should work after that

**Closed by crschnick** 2024-02-28 13:32 UTC
