### ISSUE TITLE
Bug: Xpipe shows only white screen

### ISSUE THREAD

**Issue by rkokkelk** [xpipe-io/xpipe#65] opened 2023-07-17 08:03 UTC
Hi,

I'm very interested in XPipe to run it on my system, but when booting I only see a white screen and nothing else. This occurs when I run it from the CLI `/opt/xpipe/app/bin/xpiped` and when using the Dekstop icon. 

I'm running:
* Pop!_OS 22.04 LTS
* 64 bits Intel
* Installed via *deb package
* Version: `1.3.2`

When run from the CLI the only output is:

```
[mode] Initial setup
```

If you need any further information, please let me known. 

![image](https://github.com/xpipe-io/xpipe/assets/9407618/d8c8aea8-e1f8-4ecf-a4c1-e4eac8435c0b)

**Comment by rkokkelk** [comment] 2023-07-17 08:07
Underlying functionality seems to work, because when I try to close the app, it shows the following pop up. But again this only shows a white screen.

![image](https://github.com/xpipe-io/xpipe/assets/9407618/ca685c04-ab0a-4b89-92a0-d9cba0c78835)

**Comment by crschnick** [comment] 2023-07-17 17:42
That is very weird, I have never seen that before. There is a debug mode script under `/opt/xpipe/app/scripts/xpiped_debug.sh` that will print a lot of information in the console.

But I don't think they will be any error shown, otherwise there would be a error reporter window showing up. Let me try to reproduce that, I have to set up a vm for that.

**Comment by crschnick** [comment] 2023-07-17 17:52
Meanwhile, you could try disabling hardware acceleration in JavaFX by launching it with the following command: `/opt/xpipe/app/bin/xpiped -Dprism.order=j2d`

**Comment by rkokkelk** [comment] 2023-07-17 19:15
I just gone on holiday today, so I'll definitely try it when I come back in roughly 3 weeks.

**Comment by crschnick** [comment] 2023-07-17 19:22
Haha ok then, have fun during your holidays. I just tested it myself on a blank PopOS 22.04 VM and it rendered correctly, so I guess we will need to investigate that bit further when you come back.

**Comment by rkokkelk** [comment] 2023-07-28 19:25
Manually running it with `/opt/xpipe/app/bin/xpiped -Dprism.order=j2d` did solve the issue. 

![image](https://github.com/xpipe-io/xpipe/assets/9407618/73eb3e7c-7e86-4d7d-847b-83b60d9afe66)

**Comment by crschnick** [comment] 2023-07-28 19:28
Then it must be some graphics driver compatibility issue with JavaFX, I have seen a few of those over the years (They are very rare however).

Note that since you opened this issue, there have been a few new releases of xpipe with various improvements. I don't think they will fix the display issue though.

**Comment by crschnick** [comment] 2023-07-28 19:30
There is also a switch `xpiped -Dio.xpipe.app.debugPlatform=true` to print debug output for the graphics platform in case you're interested in the detailed error

**Comment by rkokkelk** [comment] 2023-07-29 09:20
These are the error I see, basically whenever `ES2ResourceFactory: Prism - createStockShader: FillPgram_Color.frag` or `Error loading stock shader FillPgram_Color` is seen in the logs the following stack traces are logged. 

```java
11:16:25:717 - debug: Set content scene
11:16:25:718 - debug: Set content reload listener
11:16:25:718 - info: Application window initialized
11:16:25:720 - info: Window setup complete
11:16:26:539 - info: ES2ResourceFactory: Prism - createStockShader: FillPgram_Color.frag
11:16:26:542 - error: java.lang.reflect.InvocationTargetException
11:16:26:542 - error:   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
11:16:26:542 - error:   at java.base/java.lang.reflect.Method.invoke(Method.java:578)
11:16:26:542 - error:   at javafx.graphics@20.0.1/com.sun.prism.es2.ES2ResourceFactory.createStockShader(ES2ResourceFactory.java:324)
11:16:26:542 - error:   at javafx.graphics@20.0.1/com.sun.prism.impl.ps.BaseShaderContext.getPaintShader(BaseShaderContext.java:269)
11:16:26:542 - error:   at javafx.graphics@20.0.1/com.sun.prism.impl.ps.BaseShaderContext.validatePaintOp(BaseShaderContext.java:500)
11:16:26:542 - error:   at javafx.graphics@20.0.1/com.sun.prism.impl.ps.BaseShaderContext.validatePaintOp(BaseShaderContext.java:369)
11:16:26:542 - error:   at javafx.graphics@20.0.1/com.sun.prism.impl.ps.BaseShaderGraphics.renderGeneralRoundedPgram(BaseShaderGraphics.java:927)
11:16:26:542 - error:   at javafx.graphics@20.0.1/com.sun.prism.impl.ps.BaseShaderGraphics.renderGeneralRoundedRect(BaseShaderGraphics.java:628)
11:16:26:543 - error:   at javafx.graphics@20.0.1/com.sun.prism.impl.ps.BaseShaderGraphics.fillRect(BaseShaderGraphics.java:1535)
11:16:26:543 - error:   at javafx.graphics@20.0.1/com.sun.javafx.sg.prism.NGRegion.renderBackgroundRectanglesDirectly(NGRegion.java:1112)
11:16:26:543 - error:   at javafx.graphics@20.0.1/com.sun.javafx.sg.prism.NGRegion.renderBackgroundRectangle(NGRegion.java:852)
11:16:26:543 - error:   at javafx.graphics@20.0.1/com.sun.javafx.sg.prism.NGRegion.renderAsRectangle(NGRegion.java:754)
11:16:26:543 - error:   at javafx.graphics@20.0.1/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:575)
11:16:26:543 - error:   at javafx.graphics@20.0.1/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2074)
11:16:26:543 - error:   at javafx.graphics@20.0.1/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
11:16:26:543 - error:   at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:480)
11:16:26:543 - error:   at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:329)
11:16:26:543 - error:   at javafx.g11:16:26:876 - error: java.lang.reflect.InvocationTargetException
11:16:26:877 - error:   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
11:16:26:877 - error:   at java.base/java.lang.reflect.Method.invoke(Method.java:578)
11:16:26:877 - error:   at javafx.graphics@20.0.1/com.sun.prism.es2.ES2ResourceFactory.createStockShader(ES2ResourceFactory.java:324)
11:16:26:877 - error:   at javafx.graphics@20.0.1/com.sun.prism.impl.ps.BaseShaderContext.getPaintShader(BaseShaderContext.java:269)
11:16:26:877 - error:   at javafx.graphics@20.0.1/com.sun.prism.impl.ps.BaseShaderContext.validatePaintOp(BaseShaderContext.java:500)
11:16:26:877 - error:   at javafx.graphics@20.0.1/com.sun.prism.impl.ps.BaseShaderContext.validatePaintOp(BaseShaderContext.java:369)
11:16:26:878 - error:   at javafx.graphics@20.0.1/com.sun.prism.impl.ps.BaseShaderGraphics.renderGeneralRoundedPgram(BaseShaderGraphics.java:927)
11:16:26:878 - error:   at javafx.graphics@20.0.1/com.sun.prism.impl.ps.BaseShaderGraphics.renderGeneralRoundedRect(BaseShaderGraphics.java:628)
11:16:26:878 - error:   at javafx.graphics@20.0.1/com.sun.prism.impl.ps.BaseShaderGraphics.fillRect(BaseShaderGraphics.java:1535)
11:16:26:878 - error:   at javafx.graphics@20.0.1/com.sun.javafx.sg.prism.NGRegion.renderBackgroundRectanglesDirectly(NGRegion.java:1112)
11:16:26:878 - error:   at javafx.graphics@20.0.1/com.sun.javafx.sg.prism.NGRegion.renderBackgroundRectangle(NGRegion.java:852)
11:16:26:878 - error:   at javafx.graphics@20.0.1/com.sun.javafx.sg.prism.NGRegion.renderAsRectangle(NGRegion.java:754)
11:16:26:878 - error:   at javafx.graphics@20.0.1/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:575)
11:16:26:878 - error:   at javafx.graphics@20.0.1/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2074)
11:16:26:878 - error:   at javafx.graphics@20.0.1/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
11:16:26:878 - error:   at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:480)
11:16:26:878 - error:   at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:329)
11:16:26:879 - error:   at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:92)
11:16:26:879 - error:   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
11:16:26:879 - error:   at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
11:16:26:879 - error:   at javafx.graphics@20.0.1/com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
11:16:26:879 - error:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
11:16:26:879 - error:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
11:16:26:879 - error:   at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:126)
11:16:26:879 - error:   at java.base/java.lang.Thread.run(Thread.java:1623)
11:16:26:879 - error: Caused by: java.lang.RuntimeException: Error creating vertex shader
11:16:26:879 - error:   at javafx.graphics@20.0.1/com.sun.prism.es2.ES2Shader.createFromSource(ES2Shader.java:132)
11:16:26:879 - error:   at javafx.graphics@20.0.1/com.sun.prism.es2.ES2Shader.createFromSource(ES2Shader.java:173)
11:16:26:879 - error:   at javafx.graphics@20.0.1/com.sun.prism.es2.ES2ResourceFactory.createShader(ES2ResourceFactory.java:235)
11:16:26:880 - error:   at javafx.graphics@20.0.1/com.sun.prism.shader.FillPgram_Color_Loader.loadShader(FillPgram_Color_Loader.java:47)
11:16:26:880 - error:   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
11:16:26:880 - error:   ... 24 moreraphics@20.0.1/com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:92)
11:16:26:543 - error:   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
11:16:26:543 - error:   at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
11:16:26:543 - error:   at javafx.graphics@20.0.1/com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
11:16:26:544 - error:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
11:16:26:544 - error:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
11:16:26:544 - error:   at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:126)
11:16:26:544 - error:   at java.base/java.lang.Thread.run(Thread.java:1623)
11:16:26:544 - error: Caused by: java.lang.RuntimeException: Error creating vertex shader
11:16:26:544 - error:   at javafx.graphics@20.0.1/com.sun.prism.es2.ES2Shader.createFromSource(ES2Shader.java:132)
11:16:26:544 - error:   at javafx.graphics@20.0.1/com.sun.prism.es2.ES2Shader.createFromSource(ES2Shader.java:173)
11:16:26:544 - error:   at javafx.graphics@20.0.1/com.sun.prism.es2.ES2ResourceFactory.createShader(ES2ResourceFactory.java:235)
11:16:26:544 - error:   at javafx.graphics@20.0.1/com.sun.prism.shader.FillPgram_Color_Loader.loadShader(FillPgram_Color_Loader.java:47)
11:16:26:544 - error:   at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
11:16:26:544 - error:   ... 24 more
...
11:16:26:880 - error: java.lang.InternalError: Error loading stock shader FillPgram_Color
11:16:26:880 - error:   at javafx.graphics@20.0.1/com.sun.prism.es2.ES2ResourceFactory.createStockShader(ES2ResourceFactory.java:327)
11:16:26:880 - error:   at javafx.graphics@20.0.1/com.sun.prism.impl.ps.BaseShaderContext.getPaintShader(BaseShaderContext.java:269)
11:16:26:880 - error:   at javafx.graphics@20.0.1/com.sun.prism.impl.ps.BaseShaderContext.validatePaintOp(BaseShaderContext.java:500)
11:16:26:880 - error:   at javafx.graphics@20.0.1/com.sun.prism.impl.ps.BaseShaderContext.validatePaintOp(BaseShaderContext.java:369)
11:16:26:880 - error:   at javafx.graphics@20.0.1/com.sun.prism.impl.ps.BaseShaderGraphics.renderGeneralRoundedPgram(BaseShaderGraphics.java:927)
11:16:26:880 - error:   at javafx.graphics@20.0.1/com.sun.prism.impl.ps.BaseShaderGraphics.renderGeneralRoundedRect(BaseShaderGraphics.java:628)
11:16:26:880 - error:   at javafx.graphics@20.0.1/com.sun.prism.impl.ps.BaseShaderGraphics.fillRect(BaseShaderGraphics.java:1535)
11:16:26:881 - error:   at javafx.graphics@20.0.1/com.sun.javafx.sg.prism.NGRegion.renderBackgroundRectanglesDirectly(NGRegion.java:1112)
11:16:26:881 - error:   at javafx.graphics@20.0.1/com.sun.javafx.sg.prism.NGRegion.renderBackgroundRectangle(NGRegion.java:852)
11:16:26:881 - error:   at javafx.graphics@20.0.1/com.sun.javafx.sg.prism.NGRegion.renderAsRectangle(NGRegion.java:754)
11:16:26:881 - error:   at javafx.graphics@20.0.1/com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:575)
11:16:26:881 - error:   at javafx.graphics@20.0.1/com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2074)
11:16:26:881 - error:   at javafx.graphics@20.0.1/com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1966)
11:16:26:881 - error:   at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:480)
11:16:26:881 - error:   at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:329)
11:16:26:881 - error:   at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:92)
11:16:26:881 - error:   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
11:16:26:881 - error:   at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
11:16:26:881 - error:   at javafx.graphics@20.0.1/com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
11:16:26:882 - error:   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
11:16:26:882 - error:   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
11:16:26:882 - error:   at javafx.graphics@20.0.1/com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:126)
11:16:26:882 - error:   at java.base/java.lang.Thread.run(Thread.java:1623)


```

**Comment by crschnick** [comment] 2023-07-29 09:38
Alright, I will see how I can forward that to the JavaFX development team

**Comment by crschnick** [comment] 2023-08-22 09:31
So I reported it and it was accepted, so let see what will happen: https://bugs.java.com/bugdatabase/view_bug?bug_id=JDK-8314729

**Comment by crschnick** [comment] 2023-09-27 05:24
I'm closing this as the java bug database issue that this is linked to describes this as a driver issue where they can't do anything about it. Since this isn't the first time that nvidia graphics drivers cause issues on Linux systems, I guess it makes sense.

**Closed by crschnick** 2023-09-27 05:24 UTC
Labels: bug
