### ISSUE TITLE
[Feature Request] QNAP Docker support

### ISSUE THREAD

**Issue by hanskokx** [xpipe-io/xpipe#145] opened 2023-12-28 21:59 UTC
When I connect to my QNAP server, the Docker subsystem is not recognized. I would like to be able to manage my Docker containers on my QNAP via XPipe.

![image](https://github.com/xpipe-io/xpipe/assets/1911919/b7765e43-a4b2-4bb0-a306-401813fc8a82)
![image](https://github.com/xpipe-io/xpipe/assets/1911919/d54d0347-2334-4d1c-832e-437157d143a4)

**Comment by crschnick** [comment] 2023-12-28 22:05
Hmm, the only thing xpipe does to verify whether docker is available is to run `docker --help` and check the exit code. Maybe something when wrong there? You can try go to Settings -> Troubleshoot -> Launch in debug mode and see exactly what is getting executed and returned.

**Comment by hanskokx** [comment] 2023-12-28 22:09
Maybe it's not getting a proper shell first? I'm not sure. Details below.

<details>

```
17:06:48:080 - trace: [proc] Starting command execution ... {
    baseCommand=docker --help
    shellType=sh
    elevated=false
    workingDirectory=null
}
17:06:48:083 - trace: [proc] Writing line {
    line=echo 'a03b53cf-e4c1-44a2-b39b-0ad2f37d9727';echo '7a0f426d-088b-4d8e-9b7c-c2a3b75af24a' 1>&2;docker --help;echo '85431907-e403-4048-a01f-21744706e609'${?}END;echo '0dfd651f-6b20-42a6-93d3-a87802b89765' 1>&2
}
17:06:48:105 - trace: [proc] Stdout finished. Reading exit code ...
17:06:48:105 - trace: [proc] Read: 127END
17:06:48:105 - debug: [proc] Command finished {
    command=docker --help
    finishReason=NORMAL_FINISH
    exitCode=127
}
17:06:48:106 - trace: [proc] Read stdout {
    output=
}
17:06:48:107 - trace: [proc] Stderr finished {
    finishReason=NORMAL_FINISH
}
17:06:48:108 - trace: [proc] Command state switched to finished
17:06:48:109 - trace: [proc] Read stderr {
    output=-sh: line 19: docker: command not found
}
```

</details>

**Comment by crschnick** [comment] 2023-12-28 22:11
What is the login shell of your system? Ideally you should connect to that shell type to get all the shell profiles executed

**Comment by hanskokx** [comment] 2023-12-28 22:12
`/bin/sh`, but `/usr/bin/zsh` is also available.

**Comment by crschnick** [comment] 2023-12-28 22:16
Are all the profile files sourced properly when you manually startup a login shell with `sh -l`?

**Comment by crschnick** [comment] 2023-12-28 22:17
For better reproduction, you can try manually connecting with `ssh -T user@host` because that is what xpipe does internally. The exact command used to connect should also be found somewhere in the debug output

**Comment by hanskokx** [comment] 2023-12-28 22:21
It looks like `ssh -T` gets me to busybox, not a proper shell.

**Comment by crschnick** [comment] 2023-12-28 22:28
hmm, any idea why? I don't have QNAP setup to test that. Essentially, xpipe she's the same thing as when you manually open with `ssh -T`. If you somehow managed to make it start a proper shell, it should work.

**Comment by hanskokx** [comment] 2023-12-28 22:33
That's the funny thing. It detects zsh properly and tapping on it will drop me into a zsh shell (but `SHELL=/bin/sh` still).

**Comment by hanskokx** [comment] 2023-12-28 22:36
Aha - if I manually set the `PATH` variable in the init script for one of the shells, it finds docker.

**Comment by crschnick** [comment] 2023-12-28 22:40
Interesting. Honestly these busybox setups are usually not designed for having extensive profile scripts that cover all situations, so I can see why there are some problems like that. If you somehow get it running without explicitly specifying the path, feel free to share.

**Comment by hanskokx** [comment] 2023-12-28 22:41
Setting the `PATH` is a decent enough solution for me 🤷🏻‍♂️

**Comment by crschnick** [comment] 2023-12-29 04:12
So I played around a bit with better PATH initialization (hopefully). You can try whether the latest version of https://github.com/xpipe-io/xpipe-ptb work for you without explicitly setting the path

**Comment by hanskokx** [comment] 2024-01-04 17:47
Just getting back to this after some Holiday stuff. What settings should I 
clear before trying this build to ensure that I'm testing properly? Just 
the env vars I've set?

**Comment by crschnick** [comment] 2024-01-04 17:52
Yes that should be enough.

You can try the different variations of shells that you have available, e.g. test with sh and zsh. If you click on `add` -> `search automatically` -> then select the actual shell environment on your system as the target, e.g. the sh or zsh environment, it will use that shell to search for docker containers. So if it at least works in one of these shells, you can use that one to access docker.

**Comment by crschnick** [comment] 2024-01-20 20:31
I guess we can close this then as it is at least somehow manageable with a custom PATH setup.

**Closed by crschnick** 2024-01-20 20:31 UTC

**Comment by hanskokx** [comment] 2024-01-20 20:33
Sorry! I've been packing for an international move. I'll have more time once I arrive later this week, or next.
Message ID: ***@***.***>
[ee3f7470-1e93-47e1-8353-0ad03ba45c36]

**Comment by crschnick** [comment] 2024-01-20 20:34
Oh yeah sure no worries, you can reopen this at any time
