### ISSUE TITLE
powershell remote (PSRemoting)

### ISSUE THREAD

**Issue by inter1965** [xpipe-io/xpipe#17] opened 2023-04-07 04:13 UTC
Is it possible to add powershell remote (WS-Management Remoting) for remote host and remote shell, PowerShell 7+ is also available under linux and macOS;
PSRemoting also has the ability to send/fecth files from the remote host.

**Comment by crschnick** [comment] 2023-04-07 05:30
Looking at this from a theoretical standpoint, it should be possible. I have to try it out for myself though to see how it actually works as I've never used it.
The issue is that currently powershell support is somewhat linked to Windows as some features can't be implemented in pure powershell and are delegated to cmd in this case. I would have to rework this aspect to look for another shell to delegate to on Linux and macOS.

**Comment by crschnick** [comment] 2023-04-08 14:47
Ok, I took a look at it and tested it on my own server and this should be possible. The main hurdle is that it is kinda buggy, at least on my powershell version (5.1). I have to see whether I'm able to work around the issues.

**Comment by crschnick** [comment] 2023-04-10 14:18
PowerShell remoting is too buggy to be used currently. There are several smaller bugs that I can work around, but somehow all output of cmdlets is missing when run in a remote session with no console allocated (i.e. when a headless powershell process is spawned). This is a cmdlet issue, as commands like `cmd /c echo hello world` work fine on the remote session while `Write-Output` and others do not.

**Comment by crschnick** [comment] 2023-04-10 15:23
If anyone who knows more about powershell than me has some ideas on diagnosing were the cmdlet output goes, help would be very much appreciated here.

**Comment by inter1965** [comment] 2023-04-11 08:53
I think a better way is to use the [api](https://docs.microsoft.com/en-us/dotnet/api/system.management.automation?view=powershellsdk-7.0.0)
[pypsrp](https://github.com/jborean93/pypsrp) is a good example.

**Comment by crschnick** [comment] 2023-04-11 21:18
The approach behind X-Pipe is to utilize CLI tools, that's what makes it different from other ones. The whole project is architectured in a way that makes it super easy to add new types of remote shell connections but is not made to integrate with APIs.
And I'm close to the finish line here, almost everything works except the cmdlet output. Sadly I'm also not able to run cmd in the remote session as running interactive commands in remote sessions is also not supported.

**Comment by crschnick** [comment] 2023-04-13 03:49
You can try out the feature at https://github.com/xpipe-io/xpipe_staging/releases by downloading a portable release from there. It is a basic implementation but it can easily be improved.

**Comment by crschnick** [comment] 2023-04-21 08:14
This has been released now in 0.5.36. So if you encounter any issues you can report them here

**Comment by crschnick** [comment] 2023-09-27 05:26
Whoops, it seems like I forgot to close this issue as completed. I'm doing this now. In the latest release 1.6 I also fixed a couple of issues with Powershell Remoting, so it should work properly now

**Closed by crschnick** 2023-09-27 05:26 UTC
Labels: enhancement
