### ISSUE TITLE
Auth Problem when using the google-authenticator pam module

### ISSUE THREAD

**Issue by Samurai1201** [xpipe-io/xpipe#83] opened 2023-08-21 06:50 UTC
I have set up a server with password auth to also request a totp token from the user at login. I used to google-authenticator pam module to do so. When using no gateway to add the ssh connection, i get the proper response asking for the totp key, but even when entered correctly it returns the error

Shell opener command was unsuccessful:
Received disconnect from xxx.xxx.xxx.xxx port 22:2: Too many authentication failures
Disconnected from xxx.xxx.xxx.xxx port 22

( I just removed the ip for security reasons )

When using software like winscp this setup works nicely for me 

Thanks for your help and the work on this really cool project

**Comment by crschnick** [comment] 2023-08-21 06:53
The passcode changes for every connection attempt, right?

**Comment by Samurai1201** [comment] 2023-08-21 06:54
Yeah, it changes every 30 seconds

**Comment by crschnick** [comment] 2023-08-21 06:55
That might be caused by caching the prompted password for convenience reasons. I didn't account for changing passwords here. What is the prompt message, maybe I can not cache passwords when the prompt does not contain the word password.

**Comment by Samurai1201** [comment] 2023-08-21 06:58
It prompts for
Verification code:

**Comment by crschnick** [comment] 2023-08-21 22:33
As a follow up, how does that system handle sudo elevation? Is there a separate password?

**Comment by Samurai1201** [comment] 2023-08-22 05:53
Sorry for the slow response, im running short on time this week … I will get back to you when everythings back to normal

**Comment by crschnick** [comment] 2023-09-10 07:53
So anyways, I worked a bit on this issue in the later staging test release (https://github.com/xpipe-io/xpipe_staging/releases/tag/1.6.0). It now should prompt every time for verification codes. To improve the user experience here, I plan to somehow try to get lucky and cache the last code for maybe ten seconds or so.

**Comment by crschnick** [comment] 2023-11-18 12:09
Closing this after a while as it should be resolved. When the askpass query contains the words verification code, it will not cache any passwords.

**Closed by crschnick** 2023-11-18 12:09 UTC
