### ISSUE TITLE
Better (simpler?) custom termianl control, so that ssh_agent is effective

### ISSUE THREAD

**Issue by tolgaulas** [xpipe-io/xpipe#224] opened 2024-04-07 12:28 UTC
I discovered that (after some updates may be, not so sure) xpipe opened cmd based sessions does not use key_agent, yet normal ssh to host from a simple cmd environment does.. 

I dug a little, did small reverse engineering.. what `custom` does in $CMD environment, it prepares bunch of bat files that recursively executes themselves, and finally it calls a custom ssh command in CMD /K shell environment.. 
```
...bunch of set...ssh -oNumberOfPasswordPrompts=3 "<myhost>" -oStrictHostKeyChecking=accept-new -oRemoteCommand=none -oNoHostAuthenticationForLocalhost=yes -t -F "<the custom config of the host definition>" bash --rcfile "/tmp/exec-1471471777.sh"
```
so that's custom config file does prevent to use my default SSH config, hence my identity lines in my default config, preventing my public key is not exposed to remote...

Some suggestions to overcome this
 - provide a simpler/more detailed variables option to custom terminal for fine grain on what's going to pass on etc
 - provide an option to use/merge the existing .ssh_conf file in effect
 - provide an option to define a global .ssh_config (which can use the existing systems ssh_conf) so that host specific ssh_config to be merged.

**Comment by crschnick** [comment] 2024-04-07 12:35
So the problem is that it uses -F <config file>, which effectively replaces your system ssh config? When this option is active, it replaces the system SSH config, which you should find somewhere at C:\ProgramData. I think this has not caused issues before because most people have their config options defined in the user config at `~\.ssh\config`, which should still be applied.

To fix this, I can just `Include` the system config in the generated config file, that should properly apply it.

**Comment by crschnick** [comment] 2024-04-07 12:59
On Windows that would be `%USERPROFILE%\.ssh\config`

**Comment by crschnick** [comment] 2024-04-07 13:55
So in theory, you *should* be able to put your agent configuration into that user config file and it should work fine with xpipe until this is properly fixed.

**Comment by crschnick** [comment] 2024-04-07 16:53
So your agent settings are in the user config at `%USERPROFILE%\.ssh\config` and it doesn't work with xpipe? According to the ssh manpage it should apply that normally, only the system config in Program Data should not be applied, but that might be a Windows-specific difference. I will have to test that

**Comment by crschnick** [comment] 2024-04-07 18:08
Yeah according to the SSH documentation it should work, so that one is probably wrong then for Windows. I will just fix this properly in the next release, was just looking for a temporary quick fix that you can use.

**Comment by crschnick** [comment] 2024-04-07 20:01
Alright it seems like I got it wrong initially when scanning the manpages. I somehow interpreted the line `If a configuration file is given on the command line, the system-wide configuration file (/etc/ssh/ssh_config) will be ignored.` as that the -F option replaces the system config, not user config. But the sentence before that says what is actually happening and I somehow ignored that. Should have read that more carefully.

But yes, the fix will just include the user config.

**Comment by crschnick** [comment] 2024-04-13 18:29
This should now be fixed in XPipe 9 at https://github.com/xpipe-io/xpipe-ptb

I will have to test it thoroughly myself because I had to rewrite many parts for the config handling as there were several issues with it.

**Closed as completed** 2024-04-14 02:30 UTC
