### ISSUE TITLE
Existing Connections on ssh user config

### ISSUE THREAD

**Issue by meska** [xpipe-io/xpipe#248] opened 2024-05-06 08:47 UTC
Hello, 
I have many ssh connections configured on `~/.ssh/config`, xPipe founds them and when I move one or more to my xPipe tree are these copied or only linked? Because Enabling  GitHub sync, only the tree is synched, not the connections inside.

**Comment by tacaly** [comment] 2024-05-06 16:33
You could have the file synchronized via the Vault. Then simply select the file from the local storage. 
![ssh_config](https://github.com/xpipe-io/xpipe/assets/167714372/67991c42-8b5b-448a-a2f7-a5eba7bcc94e)

Hope this will help you.

**Comment by meska** [comment] 2024-05-07 08:05
I can try it , but ssh_config was already synchronised ( via Syncthing ) and on the same place on both machines.

**Comment by crschnick** [comment] 2024-05-07 08:10
Yeah I think the problem here is that xpipe does not automatically sync any config connections in git as long as the config file itself is also not managed by xpipe via git.

I guess in most cases this is the correct behavior as it is fairly unlikely that the config file exists on the other systems at exactly the same location. In your case it's a little bit unfortunate though. You can try adding the config file to the xpipe git repository though.

**Comment by meska** [comment] 2024-05-07 08:34
Ok, if I do manually I have the config file location option, but xPipe already added all the connections ( I have many ) automatically and I can move them around the connection tree but there is no option to sync.

<img width="642" alt="image" src="https://github.com/xpipe-io/xpipe/assets/276923/a62811bd-6418-40c0-be29-3d0631dafb48">

**Comment by meska** [comment] 2024-05-07 08:54
So this is what I did: 
- I installed xPipe
- Automatically xPipe found all my connections inside ~./ssh/config and put them inside the 'Default' branch
- I created other branches to make some order and by clicking on the 3 dots and the move function next to the various connections I moved them to the new branches of xPipe
- I activated git synchronisation 
- I installed on another computer
- The synchronisation only synchronised the branch names but not the connections moved into the branches from the first computer.

It would probably be useful to show a warning that when I move from ssh config, git synchronisation should be activated first.

Another little problem ( I think because both computers are always on ) is that there is no option force a merge.

<img width="610" alt="image" src="https://github.com/xpipe-io/xpipe/assets/276923/121ced16-22fa-4897-b3ef-0a4a157ed474">

**Comment by crschnick** [comment] 2024-05-07 08:57
Oh yeah the categories, or as you refer to them as branches, need to be designated as shared. If you right click them, there should be an option to add them to the git repository.

The warning that git synchronization should be enabled first as a good point, I can add that.

The force merge problem is the same thing with the language, there is an option to force merge, about that assumes that your good client is in english. I will fix that in the next release

**Comment by meska** [comment] 2024-05-07 09:02
> Oh yeah the categories, or as you refer to them as branches, need to be designated as shared. If you right click them, there should be an option to add them to the git repository.

yes, the categories were set as shared, in fact they synchronised, but empty :)

> 
> The warning that git synchronization should be enabled first as a good point, I can add that.
> 
> The force merge problem is the same thing with the language, there is an option to force merge, about that assumes that your good client is in english. I will fix that in the next release

Great, not a blocking problem, if you need more info or logs, I am at your disposal.

**Comment by tacaly** [comment] 2024-05-12 13:41
Take a look at release version 9.2: https://github.com/xpipe-io/xpipe/releases/tag/9.2
The first original issue is marked as "works as intended", and the second is "fixed in the next release".

Feel free to open another issue, or reopen this one if you need further help.

**Closed by tacaly** 2024-05-12 13:41 UTC
Labels: bug, works as intended, fixed in next release
